language: objective-c

branches:
 only:
 - master

xcode_workspace: Connect.xcworkspace
xcode_scheme: Connect
xcode_sdk: iphonesimulator9.3
osx_image: xcode7.3

script:
- xcodebuild clean build test -workspace APITestDemo.xcworkspace -scheme APITestDemo_MS
